name = "shaman"
kind = "dark"

[base]
bg = "#001015"
fg = "#53FBDA"
muted = "#405555"
subtle = "#223133"
surface = "#071411"
surface_alt = "#0b1c18"
border = "#2B3A30"
border_active = "#53FBDA"
selection = "#415555"
cursor = "#4AFCD6"

[accent]
blue = "#869A86"
cyan = "#19655D"
cyan_bright = "#90FDD5"
green = "#2CA940"
yellow = "#90FDD5"
yellow_bright = "#90FDD5"
orange = "#9D5900"
orange_bright = "#9D5900"
red = "#B2322D"
purple = "#53FBDA"
pink = "#53FBDA"
magenta = "#1298FF"
teal = "#19655D"
aqua = "#90FDD5"
sage = "#869A86"

[semantic]
ok = "#2CA940"
warn = "#90FDD5"
error = "#B2322D"
info = "#19655D"
hint = "#53FBDA"

[prompt]
directory = "#869A86"
repo = "#19655D"
branch = "#90FDD5"
status_ok = "#2CA940"
status_error = "#B2322D"
duration = "#90FDD5"
env = "#53FBDA"
runtime = "#9D5900"
symbol = "#53FBDA"

[tmux]
status_bg = "#001011"
status_fg = "#53FBDA"
status_muted = "#405555"
session_bg = "#2CA940"
session_fg = "#001011"
window_active_bg = "#071411"
window_active_fg = "#53FBDA"
window_inactive_bg = "#001011"
window_inactive_fg = "#405555"
segment_info_bg = "#19655D"
segment_info_fg = "#001011"
segment_warn_bg = "#90FDD5"
segment_warn_fg = "#001011"
segment_error_bg = "#B2322D"
segment_error_fg = "#001011"
segment_time_bg = "#9D5900"
segment_time_fg = "#53FBDA"
